
export const projectsList = [
{
    slug: 'rechitsa',
    name: 'Очистные сооружения города Речица',
    location: 'г. Речица',
    region: 'Гомельская обл.',
    desc: 'Биологическая очистка хозяйственно-бытовых и производственных сточных вод города с выпуском в реку Днепр. Год постройки — 2026.',
    category: 'Коммунальное хозяйство',
    badge: 'Гомельская область | 18 000 м³/сут',
    capacity: '18 000 м³/сут',
    video: '/videos/hero/rechitsa_230926.mp4',
    poster: '/videos/hero/rechitsa_230926.jpg',
    tags: ['Биоочистка', 'Городские стоки'],
    gallery: ['/images/projects/rechitsa/1.webp', '/images/projects/rechitsa/2.webp', '/images/projects/rechitsa/3.webp']
  },
{
    slug: 'fanipol',
    name: 'Городские очистные сооружения города Фаниполь',
    location: 'г. Фаниполь',
    region: 'Минская обл.',
    desc: 'Очистные сооружения города-спутника, реализованные с учётом развития города. Год постройки — 2025.',
    category: 'Коммунальное хозяйство',
    badge: 'Минская область, Дзержинский район | 4700 м³/сут',
    capacity: '4700 м³/сут',
    video: '/videos/hero/fanipol_230926.mp4',
    poster: '/videos/hero/fanipol_230926.jpg',
    tags: ['Биоочистка', 'Городские стоки'],
    gallery: ['/images/projects/fanipol/1.webp', '/images/projects/fanipol/2.webp', '/images/projects/fanipol/3.webp']
  },
{
    slug: 'krichev',
    name: 'Очистные сооружения города Кричев',
    location: 'г. Кричев',
    region: 'Могилёвская обл.',
    desc: 'Станция биологической очистки сточных вод города Кричева.',
    category: 'Коммунальное хозяйство',
    badge: 'Могилевская область | 4250 м³/сут',
    capacity: '4250 м³/сут',
    video: '/videos/hero/krichev_230926.mp4',
    poster: '/videos/hero/krichev_230926.jpg',
    tags: ['Биоочистка', 'Городские стоки'],
    gallery: ['/images/projects/krichev/1.webp', '/images/projects/krichev/2.webp', '/images/projects/krichev/3.webp']
  },
{
    slug: 'mstislavl',
    name: 'Очистные сооружения города Мстиславля',
    location: 'г. Мстиславль',
    region: 'Могилёвская обл.',
    desc: 'Станция очистных сооружений города Мстиславля. Год постройки — 2023.',
    category: 'Коммунальное хозяйство',
    badge: 'Могилевская область | 1800 м³/сут',
    capacity: '1800 м³/сут',
    video: '/videos/hero/mstislavl_230926.mp4',
    poster: '/videos/hero/mstislavl_230926.jpg',
    tags: ['Биоочистка', 'Городские стоки'],
    gallery: ['/images/projects/mstislavl/1.webp', '/images/projects/mstislavl/2.webp', '/images/projects/mstislavl/3.webp']
  },
{
    slug: 'skidel',
    name: 'Строительство очистных сооружений города Скидель',
    location: 'г. Скидель',
    region: 'Гродненская обл.',
    desc: 'Строительство очистных сооружений города Скиделя.',
    category: 'Коммунальное хозяйство',
    badge: 'Гродненская область | 6500 м³/сут',
    capacity: '6500 м³/сут',
    video: '/videos/hero/skidel.mp4',
    poster: '/videos/hero/skidel.jpg',
    tags: ['Строительство', 'Биоочистка'],
    gallery: ['/images/projects/skidel/1.webp', '/images/projects/skidel/2.webp', '/images/projects/skidel/3.webp']
  },
{
    slug: 'krasnoe',
    name: 'Реконструкция очистных сооружений сточных вод в деревне Красное',
    location: 'д. Красное, Молодечненский р-н',
    region: 'Минская обл.',
    desc: 'Реконструкция очистных сооружений сточных вод в деревне Красное.',
    category: 'Коммунальное хозяйство',
    badge: 'Минская область, Молодечненский район | 500 м³/сут',
    capacity: '500 м³/сут',
    video: '/videos/hero/krasnoe.mp4',
    poster: '/videos/hero/krasnoe.jpg',
    tags: ['Реконструкция'],
    gallery: ['/images/projects/krasnoe/1.webp', '/images/projects/krasnoe/2.webp', '/images/projects/krasnoe/3.webp']
  },
{
    slug: 'postavy-dairy',
    name: 'Очистные сооружения Поставского молочного завода',
    location: 'Поставский молочный завод',
    region: 'Витебская обл.',
    desc: 'Очистка высококонцентрированных сточных вод молочного завода методом физико-химической и последующей биологической очистки. Год постройки — 2024.',
    category: 'Промышленность',
    badge: 'Витебская область | 600 м³/сут',
    capacity: '600 м³/сут',
    video: '/videos/hero/postavsky_230926.mp4',
    poster: '/videos/hero/postavsky_230926.jpg',
    tags: ['Физико-химическая очистка', 'Биоочистка'],
    gallery: ['/images/projects/postavy-dairy/1.webp', '/images/projects/postavy-dairy/2.webp', '/images/projects/postavy-dairy/3.webp']
  },
{
    slug: 'vitkonprodukt',
    name: 'Очистные сооружения ООО «Витконпродукт»',
    location: 'ООО «Витконпродукт»',
    region: 'Витебская обл.',
    desc: 'Очистные сооружения компактного типа с полной биологической очисткой и аэробной стабилизацией. Год постройки — 2018.',
    category: 'Промышленность',
    badge: 'Витебская область | 700 м³/сут',
    capacity: '700 м³/сут',
    video: '/videos/hero/vitkonprodukt_230926.mp4',
    poster: '/videos/hero/vitkonprodukt_230926.jpg',
    tags: ['Производственные стоки'],
    gallery: ['/images/projects/vitkonprodukt/1.webp', '/images/projects/vitkonprodukt/2.webp', '/images/projects/vitkonprodukt/3.webp']
  },
{
    slug: 'godylevo',
    name: 'Очистные сооружения в деревне Годылёво',
    location: 'д. Годылёво, Быховский р-н',
    region: 'Могилёвская обл.',
    desc: 'Очистные сооружения в деревне Годылёво Быховского района.',
    category: 'Коммунальное хозяйство',
    badge: 'Могилевская область, Быховский район | 150 м³/сут',
    capacity: '150 м³/сут',
    poster: '/images/hero/godylevo.jpg',
    tags: ['Биоочистка'],
    gallery: ['/images/projects/godylevo/1.webp']
  },
{
    id: 2,
    slug: 'agrokombinat-snov',
    poster: '/images/hero/snov.jpg',
    badge: 'Минская область, Несвижский район | 1500 м³/сут',
    name: 'Станция биологической очистки СПК «Агрокомбинат Снов»',
    location: 'Гродненская область',
    region: 'Гродненская обл.',
    desc: 'Станция биологической очистки сточных вод СПК «Агрокомбинат Снов».',
    longDesc: 'Станция биологической очистки производственных сточных вод свиноводческого комплекса производительностью 1500 м³/сутки с возможностью повторного использования очищенной воды в технологическом цикле.',
    result: 'Экономия 40%',
    category: 'АПК',
    year: '2024',
    capacity: '1 500 м³/сут',
    tags: ['Флотация', 'Биоочистка'],
    equipmentSlugs: ['flotation-units', 'bs-bio-station'],
    coords: { x: 22, y: 38 },
    task: 'Высокая концентрация органических соединений и жиров в производственных стоках свинокомплекса, угрожающая локальной экосистеме и требующая замкнутого цикла водооборота.',
    solution: 'Внедрение ступенчатых жироловок, двухфазного биореактора и напорной флотации с последующей доочисткой для повторного использования воды в технологических нуждах.',
    resultText: 'Достигнут практически нулевой сброс стоков во внешние водоёмы. 98% очищенной воды повторно используется в производственном цикле комплекса.',
    metrics: [
      { label: 'Объём стоков', value: '1 500', suffix: 'м³/сут' },
      { label: 'Рециклинг воды', value: '98', suffix: '%' },
      { label: 'Срок реализации', value: '9', suffix: 'мес' },
      { label: 'Экономия затрат', value: '40', suffix: '%' }
    ],
    beforeValue: '620 мг/л',
    afterValue: '15 мг/л',
    techStack: ['Флотация', 'Биореактор', 'IoT Cloud', 'BIM LOD500'],
    gallery: ['/images/projects/agrokombinat-snov/1.webp']
  },
{
    id: 9,
    slug: 'vitebsk-broiler',
    video: '/videos/hero/vitebsk_260926.mp4',
    poster: '/videos/hero/vitebsk_260926.jpg',
    badge: 'Витебская область | 3000 м³/сут',
    name: 'Очистные сооружения ОАО «Витебская бройлерная птицефабрика»',
    location: 'Витебская область',
    region: 'Витебская обл.',
    desc: 'Станция полной биологической очистки производственных сточных вод (3000 м³/сутки).',
    longDesc: 'Станция полной биологической очистки производственных сточных вод птицефабрики производительностью 3000 м³/сутки с системой денитрификации и УФ-обеззараживанием.',
    result: '3000 м³/сутки',
    category: 'АПК',
    year: '2021',
    capacity: '3 000 м³/сут',
    tags: ['Биоочистка', 'УФ'],
    equipmentSlugs: ['bs-bio-station'],
    coords: { x: 48, y: 12 },
    task: 'Высокая концентрация азотных соединений и органики в стоках птицефабрики, требующая денитрификации перед сбросом.',
    solution: 'Станция полной биологической очистки с зонами денитрификации, аэротенками и финишным УФ-обеззараживанием без применения хлора.',
    resultText: 'Устойчивое соответствие нормативам по азоту аммонийному и фосфору, полное исключение хлорсодержащих реагентов из технологической цепочки.',
    metrics: [
      { label: 'Производительность', value: '3 000', suffix: 'м³/сут' },
      { label: 'Удаление азота', value: '95', suffix: '%' },
      { label: 'Срок реализации', value: '11', suffix: 'мес' },
      { label: 'Дезинфекция УФ', value: '99.99', suffix: '%' }
    ],
    beforeValue: '85 мг/л азота',
    afterValue: '4 мг/л азота',
    techStack: ['Биоочистка ВС', 'Денитрификация', 'УФ-обеззараживание'],
    gallery: ['/images/projects/vitebsk-broiler/1.webp', '/images/projects/vitebsk-broiler/2.webp', '/images/projects/vitebsk-broiler/3.webp']
  }
]

export const useProjects = () => {
  const getBySlug = (slug) => projectsList.find(p => p.slug === slug)
  return { projectsList, getBySlug }
}
